- name: Enable SELinux
  selinux:
    policy: targeted
    state: enforcing

- name: Install policycoreutils-python
  package:
    name: policycoreutils-python
    state: latest

- name: Semanage add port
  shell: LANG=C semanage port --add -t http_port_t -p tcp {{ listen_port }}
  register: result
  failed_when: result.rc != 0 and "already defined" not in result.stderr
  changed_when:
    - result.rc == 0